1. Creating numpy/n-d array

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])  #List pass kari to array ban gaya
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
#2-dimensional Array
arr2=np.array([[1,2,3],[4,5,6]])  #It is called 2D array necause it has both rows(2) and columns(3)
arr2                               #first row(1,2,3) and second row(4,5,6)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.zeros((2,3))  #It means to create an array of 2 rows and 3 columns with the default value of 0
arr3                  #Update values later as needed, Create initial empty space in an array , Write code that's fast and efficient

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr5=np.identity(5)   #Matrix of 5x5 where every value is 0 except diagonally 1
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
arr6=np.arange(10) #It will create a range between 0 and 9 (10 elements)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr7=np.arange(4,12,2) #(start,end,jump)
arr7

array([ 4,  6,  8, 10])

In [9]:
arr7=np.linspace(10,20,10)  #start from 10,end on 20,Total of 10 values,all values will be equally spaced (with equal gaps).
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [10]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# **Numpy Properties and Attributes**

In [11]:
arr1

array([1, 2, 3, 4, 5])

In [12]:
arr1.shape

(5,)

In [13]:
arr2.shape

(2, 3)

In [14]:
# 3-Dimensional Array
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
"""
Think Of it as:
[
  [ [1, 2], [3, 4] ],   # First 2D block
  [ [5, 6], [7, 8] ]    # Second 2D block
]
"""
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
arr9.shape   #(2,2,2)means 2 blocks,2 rows,2 columns

(2, 2, 2)

In [18]:
arr9.ndim  #ndim is used to determine dimensions


3

In [19]:
arr6.ndim

1

In [20]:
arr1.size

5

In [21]:
arr8.size

10

In [22]:
arr5.size


25

In [23]:
arr5.itemsize  #The size (in bytes) of each element in the array.

8

In [27]:
arr4.itemsize

8

In [28]:
arr1.dtype  #dtype is used to determine the datatype

dtype('int64')

In [29]:
arr9.dtype

dtype('int64')

In [30]:
arr9.astype('float')   #astype() is used to change the type of each element in the array.

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])